config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'

  get 'transactions/create'

  get 'carts/show'

  devise_for :admins
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  namespace :admin do
    root to: 'categories#new'
    resources :categories, param: :name, only: [:new, :create, :show, :destroy] do
      resources :products do
        resources :photos
      end
    end
  end
  resources :categories, param: :name, only: [:index, :show]
  resources :products, only: [:show]
  get 'search_products', to: "products#search"
  get 'cart', to: 'cart#show'
  put 'cart/add/:product_id', to: 'cart#add', as: :add_to
  put 'cart/remove/:product_id', to: 'cart#remove', as: :remove_from

  resources :transactions, only: [:new, :create]
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    if current_user
      cart_ids = $redis.hkeys current_user_cart
    else
      init_session_cart
      cart_ids = session[:cart].keys
    end
    @products = Product.find(cart_ids)
  end

  def add
    if current_user
      cart_ids = $redis.hkeys current_user_cart
      @products = Product.find(cart_ids)
      if $redis.hexists current_user_cart, params[:product_id]
        $redis.hincrby current_user_cart, params[:product_id], 1
      else
        $redis.hset current_user_cart, params[:product_id], 1
      end
    else
      cart_ids = session["cart"].keys
      @products = Product.find(cart_ids)
      init_session_cart
      if session["cart"][params[:product_id]]
        session["cart"][params[:product_id]] += 1
      else
        session["cart"][params[:product_id]] = 1
      end
    end
    respond_to do |format|
      format.html {redirect_to product_path(params[:product_id]), alert: "Awesome! Item has been successfully added to cart!"}
      format.js
    end
  end

  def remove
    if current_user
      cart_ids = $redis.hkeys current_user_cart
      @products = Product.find(cart_ids)
      quantity = $redis.hget current_user_cart, params[:product_id]
      if quantity.to_i == 1
        $redis.hdel current_user_cart, params[:product_id]
      else
        $redis.hincrby current_user_cart, params[:product_id], -1
      end
    else
      cart_ids = session["cart"].keys
      @products = Product.find(cart_ids)
      quantity = session['cart'][params[:product_id]]
      if quantity == 1
        session["cart"].delete(params[:product_id])
      else
        session["cart"][params[:product_id]] -= 1
      end
    end
    respond_to do |format|
      format.html {redirect_to product_path(params[:product_id])}
      format.js
    end
  end

  private
  def current_user_cart
    "cart#{current_user.id}"
  end

  def init_session_cart
    unless session[:cart]
      session[:cart] = {}
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/cart/_quantity.html.slim
table.table.table-striped
  thead
    th #
    th Name
    th Price
    th Quantity
    th Add
    th Remove
    th Subtotal
  tbody
  - index = 0
  - sum = 0
  - @products.each do |product|
    tr
      - if current_user
        - if $redis.hget "cart#{current_user.id}", product.id
          - index += 1
          th = index
          td = product.name
          td = product.price
          td = $redis.hget "cart#{current_user.id}", product.id
          td = link_to "+1", add_to_path(product.id), method: :put, remote: true
          td = link_to "-1", remove_from_path(product.id), method: :put, remote: true
          - subtotal = (product.price * ($redis.hget "cart#{current_user.id}", product.id).to_i)
          td = "$#{subtotal}"
          - sum += subtotal
      - else
        - if session["cart"][product.id.to_s]
          - index += 1
          th = index
          td = product.name
          td = product.price
          td = session["cart"][product.id.to_s]
          td = link_to "+1", add_to_path(product.id), method: :put, remote: true
          td = link_to "-1", remove_from_path(product.id), method: :put, remote: true
          - subtotal = product.price * session["cart"][product.id.to_s]
          td = "$#{subtotal}"
          - sum += subtotal

  tr.thead-default id="totals"
    td colspan=5
    th Total
    th = "$#{sum}"
.container.d-flex
  - if current_user
    =link_to "Checkout", new_transaction_path, class: "btn btn-primary btn-lg ml-auto" unless current_user.get_cart_products.blank?
  - else
    =link_to "Checkout", new_transaction_path, class: "btn btn-primary btn-lg ml-auto" unless session["cart"].keys.blank?

app/views/cart/add.js.erb
$('#cart_content').html("<%= j render partial: 'quantity' %>");
$('#cart_count').html("<%= j render partial: 'application/cart_count' %>");

app/views/cart/remove.js.erb
$('#cart_content').html("<%= j render partial: 'quantity' %>");
$('#cart_count').html("<%= j render partial: 'application/cart_count' %>");

app/views/cart/show.html.slim
.container
  h1 Cart Contents
  #cart_content = render partial: 'quantity'