config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'

  get 'transactions/create'

  get 'carts/show'

  devise_for :admins
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  namespace :admin do
    root to: 'categories#new'
    resources :categories, param: :name, only: [:new, :create, :show, :destroy] do
      resources :products do
        resources :photos
      end
    end
  end
  resources :categories, param: :name, only: [:index, :show]
  resources :products, only: [:show]
  get 'search_products', to: "products#search"
  get 'cart', to: 'cart#show'
  put 'cart/add/:product_id', to: 'cart#add', as: :add_to
  put 'cart/remove/:product_id', to: 'cart#remove', as: :remove_from

  resources :transactions, only: [:new, :create]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(get_params)
    if @category.save
      redirect_to new_admin_category_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by(name: params[:name])
    @products = @category.products
  end

  private

  def get_params
    params.require(:category).permit(:name, :description)
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(name: params[:name])
    @products = @category.products
  end
end

app/views/admin/categories/new.html.slim
.container
  h1 Create a category!
  = simple_form_for @category, url: admin_categories_path, method: :post do |f|
    = f.input :name
    = f.input :description
    = f.button :submit, 'Create!'

app/views/admin/categories/show.html.slim
.container-fluid
  .category-header
    h1.display-3 = @category.name.capitalize
    p.lead = @category.description
.container-fluid
  = link_to 'Add Product', new_admin_category_product_path(@category.name), class: "btn btn-success", id: "add-product"
  .product-body
    - @products.each do |product|
      .product-box.col-4
        .image-box
          .product-image
            = filestack_image product.photos.first.url, transform: filestack_transform.resize(width:300, height:300) if product.photos.first
        h2 = link_to product.name, admin_category_product_path(@category.name, product.id)
        h3 = "$#{product.price}"
        = link_to 'Delete', admin_category_product_path(@category.name, product.id), method: :delete, class: "btn btn-warning"