config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'

  get 'transactions/create'

  get 'carts/show'

  devise_for :admins
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  namespace :admin do
    root to: 'categories#new'
    resources :categories, param: :name, only: [:new, :create, :show, :destroy] do
      resources :products do
        resources :photos
      end
    end
  end
  resources :categories, param: :name, only: [:index, :show]
  resources :products, only: [:show]
  get 'search_products', to: "products#search"
  get 'cart', to: 'cart#show'
  put 'cart/add/:product_id', to: 'cart#add', as: :add_to
  put 'cart/remove/:product_id', to: 'cart#remove', as: :remove_from

  resources :transactions, only: [:new, :create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_admin_navbar.html.slim
nav.navbar.navbar-toggleable-md.navbar-light
  button.navbar-toggler.navbar-toggler-right type="button" data-toggle="collapse" data-target="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  = link_to image_tag('bro_bags', class: "logo"), root_path
  .flex.flex-column.col-10
    .collapse.navbar-collapse id="navbarSupportedContent"
      ul.navbar-nav.d-flex.justify-content-start
        li.nav-item.p-2 = link_to 'BACKPACKS', category_path("backpacks")
        li.nav-item.p-2 = link_to 'MESSENGERS', category_path("messengers")
        li.nav-item.p-2 = link_to 'TRAVEL BAGS', category_path("travel-bags")
        - if current_admin
          li.nav-item.ml-auto.p-2 = link_to 'Sign Out', destroy_admin_session_path, method: :delete
        -else
          li.nav-item.ml-auto.p-2 = link_to 'Admin Sign In', new_admin_session_path

        - if current_user
          li.nav-item.ml-auto.p-2 = link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          li.nav-item.ml-auto.p-2 = link_to 'User Sign In', new_user_session_path
        li.nav-item.ml-auto.p-2 id="cart_count" = render partial: 'cart_count'
    = render 'products/search_bar'
    ul.navbar-nav.d-flex.justify-content-start id = "admin-links"
      li.nav-item.p-2.admin-bar Admin mode
      li.nav-item.p-2 = link_to 'BACKPACKS', admin_category_path("backpacks"), class: "btn btn-outline-info"
      li.nav-item.p-2 = link_to 'MESSENGERS', admin_category_path("messengers"), class: "btn btn-outline-info"
      li.nav-item.p-2 = link_to 'TRAVEL BAGS', admin_category_path("travel-bags"), class: "btn btn-outline-info"

app/views/application/_cart_count.html.slim
- if current_user
  = link_to 'My Cart('+ current_user.cart_count.to_s+')', cart_path
- else
  - unless session['cart']
    - session["cart"] = {}
  = link_to 'My Cart(' + session["cart"].keys.length.to_s + ')', cart_path

app/views/application/_navbar.html.slim
nav.navbar.navbar-toggleable-md.navbar-light
  button.navbar-toggler.navbar-toggler-right type="button" data-toggle="collapse" data-target="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  = link_to image_tag('bro_bags', class: "logo"), root_path
  .flex.flex-column.col-10
    .collapse.navbar-collapse id="navbarSupportedContent"
      ul.navbar-nav.d-flex.justify-content-start
        li.nav-item.p-2 = link_to 'BACKPACKS', category_path("backpacks")
        li.nav-item.p-2 = link_to 'MESSENGERS', category_path("messengers")
        li.nav-item.p-2 = link_to 'TRAVEL BAGS', category_path("travel-bags")
        - if current_admin
          li.nav-item.ml-auto.p-2 = link_to 'Sign Out', destroy_admin_session_path, method: :delete
        -else
          li.nav-item.ml-auto.p-2 = link_to 'Admin Sign In', new_admin_session_path

        - if current_user
          li.nav-item.ml-auto.p-2 = link_to 'Sign Out', destroy_user_session_path, method: :delete
        -else
          li.nav-item.ml-auto.p-2 = link_to 'User Sign In', new_user_session_path
        li.nav-item.ml-auto.p-2 id="cart_count" = render partial: 'cart_count'
    = render 'products/search_bar'