config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'

  get 'transactions/create'

  get 'carts/show'

  devise_for :admins
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  namespace :admin do
    root to: 'categories#new'
    resources :categories, param: :name, only: [:new, :create, :show, :destroy] do
      resources :products do
        resources :photos
      end
    end
  end
  resources :categories, param: :name, only: [:index, :show]
  resources :products, only: [:show]
  get 'search_products', to: "products#search"
  get 'cart', to: 'cart#show'
  put 'cart/add/:product_id', to: 'cart#add', as: :add_to
  put 'cart/remove/:product_id', to: 'cart#remove', as: :remove_from

  resources :transactions, only: [:new, :create]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :photos, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :stock, presence: true

  has_many :orders
  has_many :users, through: :orders
  
  def self.search(param)
    return Product.none? if param.blank?

    param.strip!
    param.downcase!
    product_name_matches(param) #return this value if param is not blank
  end

  def self.product_name_matches(param)
    matches('name', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%") #% is wildcard in sql, lower method is a postgresql to lower the field_name to lowercase
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  def new
    @category = Category.find_by(name: params[:category_name])
    @product = @category.products.new
  end

  def create
    @category = Category.find_by(name: params[:category_name])
    @product = @category.products.new(get_params)
    if @product.save
      redirect_to admin_category_path(@category.name)
    else
      render :new
    end
  end

  def destroy
    @category = Category.find_by(name: params[:category_name])
    @product = @category.products.find(params[:id])
    @product.destroy
    redirect_to admin_category_path(@category.name)

  end

  def show
    @category = Category.find_by(name: params[:category_name])
    @product = @category.products.find(params[:id])
    @photos = @product.photos.all
    @photo = @photos.new

  end

  private

  def get_params
    params.require(:product).permit(:name, :description, :feature, :price, :stock)
  end


end

app/controllers/products_controller.rb
  class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end

  def search
    @products = Product.search(params[:search_param]) #search method starts here

    if @products #if product is found
      render 'search'
    else
      redirect_to root_path
    end
  end
end

app/views/products/_search_bar.html.slim
#product-lookup
  = form_tag search_products_path, method: :get do
    = text_field_tag :search_param, params[:search_param], placeholder: "Search for a product", autofocus: true
    = button_tag type: :submit, class: "btn btn-sm btn-success" do
      | Search

app/views/products/list.html.slim
= @products.each do |product|
  div
    h1 = product.name.capitalize
    hr
    h2 Description
    p = product.description
    hr
    h2 Features
    p = product.feature
    hr
    h2 Price
    p = product.price
    hr
    h2 Stock
    p = product.stock

app/views/products/search.html.slim
.container-fluid
  .category-header
    h1.display-3 Search Results
    - if @products.empty?
      p.lead Ooops, no such item matches our inventory.
    - else
      p.lead = (@products.length == 1)? "#{@products.length} item found!" : "#{@products.length} items found!"
.container-fluid
  .product-body
    - if @products
      - @products.each do |product|
        .product-box.col-4
          .image-box
            .product-image
              = filestack_image product.photos.first.url, transform: filestack_transform.resize(width:300, height:300) if product.photos.first
          h2 = link_to product.name, product_path(product.id)
          h3 = "$#{product.price}"

app/views/products/show.html.slim
.container-fluid
  .category-header
    h1.display-3 = @product.name.capitalize
    p.lead = @product.description
.container
  = link_to "Add to Cart", add_to_path(@product.id), method: :put, class: "btn btn-primary" unless @product.stock == 0
  hr
  h2 Features
  p = @product.feature
  hr
  h2 Price
  p = "$#{@product.price}"
  hr
  h2 Stock
  - if @product.stock < 4 && @product.stock > 0
    span.badge.badge-warning Low stock
    p = @product.stock
  - elsif @product.stock == 0
    span.badge.badge-danger Out of stock
  - else
    p = @product.stock
  hr
  h2 Photos
  ul.photos-container
    - @photos.each do |photo|
      .col-6 = filestack_image photo.url, transform: filestack_transform.resize(width:500, height:500), class: "photo-body"